const data = {
    products: [
        {
            name: 'SAC MICKAEL KORS',
            slug: 'SAC-MICKAEL-KORS',
            category: 'Sacs',
            image: '/images/1.jpg',
            price: 550,
            countInStock: 1,
            brand: 'mickael kors',
            rating: 4.5,
            numReviews: 10,
            description: 'Sac porté main Karlie de taille moyenne en cuir',
        },
        {
            name: 'SAC PINKO',
            slug: 'SAC-PINKO',
            category: 'Sacs',
            image: '/images/2.webp',
            price: 800,
            countInStock: 1,
            brand: 'PINKO',
            rating: 4.5,
            numReviews: 10,
            description: 'LOVE CLASSIC PUFF - Sac bandoulière',
        },
        {
            name: 'BASKETS TOMMY',
            slug: 'BASKETS-TOMMY',
            category: 'Baskets',
            image: '/images/3.png',
            price: 350,
            countInStock: 1,
            brand: 'TOMMY',
            rating: 5,
            numReviews: 5,
            description: 'Tommy Hilfiger SUPERCUP MIX - Baskets basses',
        },
        {
            name: 'VESTE AVEC CEINTURE RÉGLABLE CONTENANT DU LIN',
            slug: 'veste',
            category: 'Vestes',
            image: '/images/5.jpg',
            price: 179,
            countInStock: 1,
            brand: 'ZARA',
            rating: 4,
            numReviews: 4,
            description: 'Veste confectionnée dans une maille en mélange de lin. Col montant et manches longues terminées par un revers avec patte boutonnée',
        }
    ],
};
export default data;